config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :profiles
  resources :charts
  resources :projects
  resources :profiles_projects
  root 'profiles#index'
 

end

app/models/chart.rb
class Chart < ActiveRecord::Base
  belongs_to :project
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  has_many :profiles_projects
  has_many :projects, through: :profiles_projects

  has_attached_file :avatar, styles: { thumb: ["64x64#", :jpg, :png] }
  validates_attachment :avatar, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }


end

app/models/profiles_project.rb
class ProfilesProject < ActiveRecord::Base
  belongs_to :profile
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :profiles_projects
  has_many :profiles, through: :profiles_projects

  has_many :charts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile

  after_create :build_profile

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  def build_profile
    Profile.create(user: self)
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  self.responder = ApplicationResponder
  respond_to :html, :json

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

  before_action :find_chart, only: [:show, :edit, :update, :destroy, :add]

end

private

def chart_params
  params.require(:chart).permit(:day, :type, :description)
end

def find_chart
  @chart = Chart.find(params[:id])
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  #before_action :authenticate_user!, except: [:index]
  before_action :find_profile, only: [ :show, :edit, :update, :destroy]

  def index
    @profiles = Profile.all.paginate(page: params[:page], per_page: 5)
  end

  def show

  end

  def new
    @profile = Profile.new
  end

  def add
  end

  def edit
  end

  def create
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.json { head :no_content }
        format.js
        format.html do
          redirect_to '/'
        end
      else
        format.json { render json: @profile.errors.full_messages,
                             status: :unprocessable_entity }
      end

    end
  end

  def destroy
    @profile.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :birthday, :biography, :user_id, :avatar, :profile_id)
  end

  def find_profile
    @profile = Profile.find(params[:id])
  end

end

app/controllers/profiles_projects_controller.rb
class ProfilesProjectsController < ApplicationController

  def create
  @profiles_projects = _current_profile.profiles_projects.new(:project_id => params[:project_id])

  if @profiles_projects.save
    render status: 201, json: @profiles_projects
  end
end

  private

  def _current_profile
    @current_profile = current_user.profile
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only: [:show, :edit, :update, :destroy, :add]


  def index
    @projects = Project.all.paginate(page: params[:page], per_page: 5)
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render 'edit'
    end
  end

  def create

    @project = Project.new(project_params)
    #@project.profiles.build(params[:profile_id])

    if @project.save
      flash[:create] = 'Project created'
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @project.destroy
    flash[:destroy] = 'Delete project'
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:project_name, :project_id, :description)
  end

  def find_project
    @project = Project.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "My sample EIS App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/profiles_projects_helper.rb
module ProfilesProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
  <nav>
    <ul class="nav navbar-nav navbar-left">

    </ul>
  </nav>

    <% if user_signed_in? %>
      <div id="logo">Logged: <%= current_user.email %></div>
      <ul  class="nav navbar-nav navbar-right">
        <li><%= link_to "Profiles", profiles_path %></li>
        <li><%= link_to "Projects", projects_path %></li>
        <li><%= link_to "Edit my Profile", edit_profile_path(current_user) %></li>
        <li><%= link_to 'User edit', edit_user_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      </ul>
  <% else %>
      <ul  class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li> |
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
  <% end %>
      </ul>
</div>
</header>
  <div class="container">
<%= yield %>
  </div>
<div class="container">
<footer class="footer">
  <small>
    Created
    by <a href="https://ua.linkedin.com/in/yaroslav-zin-135864b2">yZin</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About App",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>
  </div>
</body>
</html>

app/views/profiles/_dialog.html.erb
<div class="modal fade"
     id="dialog" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true"
     data-backdrop="static"
     data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"
                data-dismiss="modal"
                aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/profiles/_form.html.erb
<%= form_for(@profile, remote: true, :html => { :role => "form" }) do |f| %>
    <div id="error_explanation" class="bg-danger text-danger">
    </div>

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :avatar, :class => "control-label" %>
          <%= f.file_field :avatar, :class => "form-control first_input"  %>
        </div>
        <div class="form-group">
          <%= f.label :name, :class => "control-label" %>
          <%= f.text_field :name, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :birthday, :class => "control-label" %>
          <%= f.text_field :birthday, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :biography, :class => "control-label" %>
          <%= f.text_field :biography, :class => "form-control" %>
        </div>
      </div>

        <div class="form-group">
          <%= f.submit  @profile.new_record? ? "Create Create" : "Update Profile", :class => "btn btn-primary" %>
        </div>
      <%= link_to 'All projects', projects_path, class: 'btn btn-info' %>
      </div>
    </div>
<% end %>

app/views/profiles/_profile.html.erb
<tr id="profile_<%= profile.id %>">
  <td><%= link_to image_tag(profile.avatar.url(:thumb), class: 'media-object'), profile.avatar.url %></td>
  <td><%= link_to "#{profile.name}", profile %></td>
  <td><%= profile.birthday %></td>
  <td><%= profile.biography %></td>


  <td>
    <% if current_user == profile.user %>
    <%= link_to 'Edit', edit_profile_path(profile), remote: true, :class => 'btn btn-sm btn-info' %>
    <% end %>
    <%= link_to 'Delete', profile, remote: true, method: :delete, :class => 'btn btn-sm btn-danger' %>

  </td>

  <td> <%= link_to 'Show', profile, class: 'btn btn-default btn-sm' %> </td>
</tr>

app/views/profiles/create.js.erb
$('#dialog').modal('toggle');
$('#profiles').append('<%= j render (@profile) %>')

app/views/profiles/destroy.js.erb
$('#profile_<%= @profile.id %>').fadeOut();

app/views/profiles/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/profiles/edit.js.erb
// Add the dialog title
$('#dialog h3').html("<i class=' glyphicon glyphicon-pencil'></i> Edit Profile");

// Render the edit form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
  $('.first_input').focus()
})

app/views/profiles/index.html.erb
<div class="all_file">

</div>
<h2 class="header1">
  <%= "All profiles" %>
</h2>
<table class="table table-condensed my_table">
  <thead>
  <tr>
    <th>
      <%= 'Image' %>
    </th>
    <th>
      <%= 'Profile name' %>
    </th>
    <th>
      <%= 'birthday' %>
    </th>
    <th>
      <%= 'biography' %>
    </th>


  </tr>
  </thead>

  <tbody id="profiles">
    <%= render @profiles %>
  </tbody>
  <%= will_paginate @profiles%>
</table>
<%= link_to 'All projects', projects_path, class: 'btn btn-info' %>
<%= render 'dialog' %>

</div>

app/views/profiles/new.html.erb
<h1>New Profile</h1>
<%= render 'form' %>

<%= link_to 'Back', profiles_path, class: 'btn btn-default btn-sm' %>

app/views/profiles/new.js.erb
// Add the dialog title
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Add New Profile");

// Render the new form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
  $('.first_input').focus()
})

app/views/profiles/show.html.erb
<div class="index_style">

  <table class="table table-condensed my_table">
    <thead>
    <tr>
      <th>
        <%= 'Image' %>
      </th>
      <th>
        <%= 'Profile name' %>
      </th>
      <th>
        <%= 'birthday' %>
      </th>
      <th>
        <%= 'biography' %>
      </th>


    </tr>
    </thead>
    <tbody>

        <tr>
          <td>
            <%= link_to image_tag(@profile.avatar.url(:thumb), class: 'media-object'), @profile.avatar.url, target: '_blank' %>
          </td>
          <td>
            <%= @profile.name %>
          </td>
          <td>
            <%= @profile.birthday %>
          </td>
          <td>
            <%= @profile.biography %>
          </td>

        </tr>

    </tbody>
  </table>

  <div>

      <%= link_to 'Edit', edit_profile_path(@profile), class: 'btn btn-success' %>

      <%= link_to 'destroy', @profile, method: :delete, data: { confirm: 'You sure?' }, class: 'btn btn-danger' %>

      <%= link_to 'Back', profiles_path, class: 'btn btn-info' %>

  </div>

<table class="table table-condensed my_table">
  <thead>
  <tr>
    <th>
      <%= 'Project name' %>
    </th>
    <th>
      <%= 'Description' %>
    </th>
    <th>
      <%= 'Created' %>
    </th>

  </tr>
  </thead>
  <thead>
  <tr>
    <%= @profile.projects.each do |project| %>
    <td>
      <%= project.project_name %>
    </td>
    <td>
      <%= project.description %>
    </td>
    <td>
      <%= project.created_at %>
    </td>
    <td>
          <%= link_to "Show", project_path(project) %>
      </td>
      <td>
          <%= link_to "Delete", project, method: :delete, data: { confirm: "You sure?" } %>
      </td>
      <td>
          <%= link_to "Update", project_path(project), :method => :update, :remote => true %>
      </td>
  </tr>
  </thead>
 <% end %>

</table>
</div>

app/views/profiles/update.js.erb
$('#dialog').modal('toggle');
$('#profile_<%= @profile.id %>').replaceWith('<%= j render (@profile) %>')

app/views/projects/_dialog.html.erb
<div class="modal fade"
     id="dialog" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true"
     data-backdrop="static"
     data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"
                data-dismiss="modal"
                aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/projects/_form.html.erb
<%= form_for(@project, remote: true, :html => { :role => "form" }) do |f| %>
    <div id="error_explanation" class="bg-danger text-danger">
    </div>

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :project_name, :class => "control-label" %>
          <%= f.text_field :project_name, :class => "form-control first_input"  %>
        </div>

        <div class="form-group">
          <%= f.label :description, :class => "control-label" %>
          <%= f.text_field :description, :class => "form-control" %>
        </div>

        <div class="actions">
          <%= f.submit %>
        </div>

      </div>
<% end %>
</div>

app/views/projects/_project.html.erb
<tr id="project_<%= project.id %>">
  <td><%= project.project_name %></td>
  <td><%= project.description %></td>


  <td>
    <%= link_to 'Edit', edit_project_path(project), remote: true, :class => 'btn btn-sm btn-info' %>
    <%= link_to 'Delete', project, remote: true, method: :delete, :class => 'btn btn-sm btn-danger' %>
    <%= link_to "Add project", profiles_projects_path(:project_id => project), :method => :post, :class => 'btn btn-success' %>
  </td>

  <td> <%= link_to 'Show', project, class: 'btn btn-default btn-sm' %> </td>
</tr>

app/views/projects/create.js.erb
$('#dialog').modal('toggle');
$('#projects').append('<%= j render (@project) %>')

app/views/projects/destroy.js.erb
$('#project_<%= @project.id %>').fadeOut();

app/views/projects/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/projects/edit.js.erb
// Add the dialog title
$('#dialog h3').html("<i class=' glyphicon glyphicon-pencil'></i> Edit Project");

// Render the edit form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
  $('.first_input').focus()
})

app/views/projects/index.html.erb
<div class="all_file">

</div>
<h2 class="header1">
  <%= "Project list" %>
</h2>
<table class="table table-condensed my_table">
  <thead>
  <tr>
    <th>
      <%= 'Project name' %>
    </th>

    <th>
      <%= 'project desript' %>
    </th>
   </tr>
  </thead>
  </tr>
  </thead>
  <%= will_paginate @projects%>
  <tbody id="projects">
  <%= render @projects %>

  </tbody>

</table>

<%= link_to 'Create project', new_project_path,class: 'btn btn-success' %>
<%= link_to 'All profiles', profiles_path, class: 'btn btn-info' %>
<%= render 'dialog' %>

</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>

<%= link_to 'Back', projects_path, class: 'btn btn-default btn-sm' %>

app/views/projects/new.js.erb
// Add the dialog title
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Add New Project");

// Render the new form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
  $('.first_input').focus()
})

app/views/projects/show.html.erb
<div class="index_style">

  <p class="show_text">
    <strong>Project name:</strong>
    <%= @project.project_name %>
  </p>
  <p class="show_text">
    <strong>Description:</strong>
    <%= @project.description %>
  </p>
  <div>

    <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-success' %>

    <%= link_to 'destroy', @project, method: :delete, data: { confirm: 'You sure?' }, class: 'btn btn-danger' %>

    <%= link_to 'Back', projects_path, class: 'btn btn-info' %>

  </div>
</div>

app/views/projects/update.js.erb
$('#dialog').modal('toggle');
$('#project_<%= @project.id %>').replaceWith('<%= j render (@project) %>')